### PR TITLE
Use `shortid` instead of random string for generateId

### PR DESCRIPTION
**Pull request by jhen0409**
We're using `generateId(id)` for each enhancer (like extension, react-native-debugger), so I think make it on here will be better.

### CODE REVIEW

**Comment by zalmoxisus** [comment]
That's good to have, but I was thinking maybe to use [`uuid`](https://www.npmjs.com/package/uuid) instead, as `socketcluster-client` is already using it. Not sure it's the case to have a better algorithm of generating an unique id as there shouldn't be so much instance ids to get overlapped, but who knows. What do you think?

**Comment by zalmoxisus** [comment]
I think we could include `uuid` right here instead of `Math.random().toString(36).substr(2)`.

**Comment by jhen0409** [comment]
I'm updated it. But actually I'm prefer to show short id on instance list, maybe [shortid](https://github.com/dylang/shortid) will be better choice?

**Comment by zalmoxisus** [comment]
`shortid` looks good. Let's go with it if you want.

**Comment by jhen0409** [comment]
Ok, it's done! :)

**Comment by zalmoxisus** [comment]
Awesome! :)
Releasing `0.1.0`.

**Pull request merged**
